default: &default
  log_level: INFO

telegram: &telegram_default
  about: Soy Donna Auchaway. Mis pronombres son neutros (elle) y soy le cyborg de Auch!
  adapter: net_http_persistent
  commands: |
    /start - Hola Donna!
    /stop - Chau Donna!
    /help - Aiuda!
    /pronombres - Mis pronombres son...
    /contame_de - Contame algo de...
    /about - Contame de vos
  description: >
    Hola, soy Donna. Mis pronombres son neutros (elle) y soy le cyborg de Auch!


    Puedo recordar tus pronombres y preferencias sobre mensajes privados de
    otrxs miembrxs del grupo, así cualquiera puede preguntarme antes de
    interactuar con vos. También podés preguntarme por quien quieras!

production:
  <<: *default
  telegram:
    <<: *telegram_default
    group: donna_test

development:
  <<: *default
  log_level: DEBUG
  telegram:
    <<: *telegram_default
    group: donna_test
