default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3

production:
  <<: *default
  database: donna_auchaway_production
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DONNA_DB_USERNAME'] %>
  password: <%= ENV['DONNA_DB_PASSWORD'] %>
